server:
  host: 0.0.0.0
  port: 8090
  cors_allowed_origins:
    - http://localhost:5173
    - http://localhost:5174
    - http://localhost:3000

auth:
  access_token_ttl: 720h
  refresh_token_ttl: 2160h
  jwt_issuer: wim

database:
  ssl_mode: disable
  connect_retries: 6
  connect_retry_initial_delay: 1s
  connect_retry_max_delay: 30s

redis:
  host: localhost
  port: 6380
  password: wim_redis_pass
  db: 0



